FROM alpine:latest

WORKDIR /app

# Variable FAIL : true ou false
ENV FAIL=false

ENTRYPOINT ["sh","-c","echo 'running test for CATALOGUE SERVICE...'; sleep 3; if [ \"$FAIL\" = \"true\" ]; then echo '❌ test for CATALOGUE SERVICE failed'; exit 1; else echo '✅ test for CATALOGUE SERVICE succeed'; exit 0; fi"]