apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: pgadmin-strip
spec:
  stripPrefix:
    prefixes:
      - /devops/api/pgadmin
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: pgadmin-headers
spec:
  headers:
    customRequestHeaders:
      X-Script-Name: "/devops/api/pgadmin"
      X-Forwarded-Proto: "https"
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: minio-strip
spec:
  stripPrefix:
    prefixes:
      - /devops/api/minio
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: minio-headers
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
    customResponseHeaders:
      Content-Security-Policy: ""