events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 80;

        # Servir uniquement le frontend statique
        location /devops/shanify {
            alias /usr/share/nginx/html;
            try_files $uri $uri/ /index.html;
        }

        location ~ ^/devops/shanify/([a-z0-9-]+)$ {
            alias /usr/share/nginx/html;
            try_files /index.html =404;
        }
    }
}