apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: site-service
  template:
    metadata:
      labels:
        app: site-service
    spec:
      containers:
      - name: site-service
        image: site-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://devops:devops123@postgres:5432/devops_db"