apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: sitebuilder
data:
  POSTGRES_DB: "sitebuilder"
  POSTGRES_USER: "postgres"
  PGADMIN_DEFAULT_EMAIL: "admin@sitebuilder.com"
  MINIO_ROOT_USER: "minioadmin"
  MINIO_BROWSER_REDIRECT_URL: "http://localhost/devops/api/minio"
  MINIO_DOMAIN: "localhost"
  DATABASE_URL: "postgresql://postgres:53c16ea5b106fc210fc811663b1dd915@postgres-service:5432/sitebuilder"
  MINIO_ENDPOINT: "minio-service:9000"
  CATALOGUE_BASE: "http://nginx-service/devops/api/catalogue-service"